AUTH0_DOMAIN_setup = 'capstone-sedhmi.us.auth0.com'
ALGORITHMS_setup = ['RS256']
API_AUDIENCE_setup = 'capstone-sedhmi'
CLIENT_ID='loGw61Usco9K60XBw03JNrcgj7nQQws5'

CASTING_ASSISTANT_JWT=''
CASTING_DIRECTOR_JWT=''
EXECUTIVE_PRODUCER_JWT=''